// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOqKY7LGC5Uhl2fAC3TRBP2jNoKfRpIMU',
    appId: '1:934761303610:web:3a02060819e5fab3612f03',
    messagingSenderId: '934761303610',
    projectId: 'subhadipofc-firebase1',
    authDomain: 'subhadipofc-firebase1.firebaseapp.com',
    storageBucket: 'subhadipofc-firebase1.appspot.com',
    measurementId: 'G-2H856QTD9W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPe0pL2gt8o3scyxrcdgr2SMkjEABnXWQ',
    appId: '1:934761303610:android:d44edb3f77abf1f4612f03',
    messagingSenderId: '934761303610',
    projectId: 'subhadipofc-firebase1',
    storageBucket: 'subhadipofc-firebase1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfge3x_UYz1ZFVU-3OguggSUSzOIzUUSc',
    appId: '1:934761303610:ios:77cd4d19454ce3a7612f03',
    messagingSenderId: '934761303610',
    projectId: 'subhadipofc-firebase1',
    storageBucket: 'subhadipofc-firebase1.appspot.com',
    iosBundleId: 'com.example.sampleapp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfge3x_UYz1ZFVU-3OguggSUSzOIzUUSc',
    appId: '1:934761303610:ios:ee5acc1a31e41fcf612f03',
    messagingSenderId: '934761303610',
    projectId: 'subhadipofc-firebase1',
    storageBucket: 'subhadipofc-firebase1.appspot.com',
    iosBundleId: 'com.example.sampleapp1.RunnerTests',
  );
}
